development:
  clients:
    default:
      database: jpg_ranger_development
      hosts:
        - 127.0.0.1:27017
test:
  clients:
    default:
      database: jpg_ranger_test
      hosts:
        - 127.0.0.1:27017
special:
  clients:
    default:
      database: jpg_ranger_special
      hosts:
        - 127.0.0.1:27017
production:
  clients:
    default:
      database: jpg_ranger
      hosts:
        - gremlin:27017
